INSERT INTO `regions`(`region_name`) VALUES ('Республика Адыгея');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Башкортостан');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Бурятия');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Алтай');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Дагестан');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Ингушетия');
INSERT INTO `regions`(`region_name`) VALUES ('Кабардино-Балкарская Республика');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Калмыкия');
INSERT INTO `regions`(`region_name`) VALUES ('Карачаево-Черкесская Республика');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Карелия');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Коми');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Марий Эл');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Мордовия');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Саха (Якутия)');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Северная Осетия - Алания');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Татарстан');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Тыва');
INSERT INTO `regions`(`region_name`) VALUES ('Удмуртская Республика');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Хакасия');
INSERT INTO `regions`(`region_name`) VALUES ('Чеченская Республика');
INSERT INTO `regions`(`region_name`) VALUES ('Чувашская Республика');
INSERT INTO `regions`(`region_name`) VALUES ('Алтайский край');
INSERT INTO `regions`(`region_name`) VALUES ('Краснодарский край');
INSERT INTO `regions`(`region_name`) VALUES ('Красноярский край');
INSERT INTO `regions`(`region_name`) VALUES ('Приморский край');
INSERT INTO `regions`(`region_name`) VALUES ('Ставропольский край');
INSERT INTO `regions`(`region_name`) VALUES ('Хабаровский край');
INSERT INTO `regions`(`region_name`) VALUES ('Амурская область');
INSERT INTO `regions`(`region_name`) VALUES ('Архангельская область');
INSERT INTO `regions`(`region_name`) VALUES ('Астраханская область');
INSERT INTO `regions`(`region_name`) VALUES ('Белгородская область');
INSERT INTO `regions`(`region_name`) VALUES ('Брянская область');
INSERT INTO `regions`(`region_name`) VALUES ('Владимирская область');
INSERT INTO `regions`(`region_name`) VALUES ('Волгоградская область');
INSERT INTO `regions`(`region_name`) VALUES ('Вологодская область');
INSERT INTO `regions`(`region_name`) VALUES ('Воронежская область');
INSERT INTO `regions`(`region_name`) VALUES ('Ивановская область');
INSERT INTO `regions`(`region_name`) VALUES ('Иркутская область');
INSERT INTO `regions`(`region_name`) VALUES ('Калининградская область');
INSERT INTO `regions`(`region_name`) VALUES ('Калужская область');
INSERT INTO `regions`(`region_name`) VALUES ('Камчатский край');
INSERT INTO `regions`(`region_name`) VALUES ('Кемеровская область');
INSERT INTO `regions`(`region_name`) VALUES ('Кировская область');
INSERT INTO `regions`(`region_name`) VALUES ('Костромская область');
INSERT INTO `regions`(`region_name`) VALUES ('Курганская область');
INSERT INTO `regions`(`region_name`) VALUES ('Курская область');
INSERT INTO `regions`(`region_name`) VALUES ('Ленинградская область');
INSERT INTO `regions`(`region_name`) VALUES ('Липецкая область');
INSERT INTO `regions`(`region_name`) VALUES ('Магаданская область');
INSERT INTO `regions`(`region_name`) VALUES ('Московская область');
INSERT INTO `regions`(`region_name`) VALUES ('Мурманская область');
INSERT INTO `regions`(`region_name`) VALUES ('Нижегородская область');
INSERT INTO `regions`(`region_name`) VALUES ('Новгородская область');
INSERT INTO `regions`(`region_name`) VALUES ('Новосибирская область');
INSERT INTO `regions`(`region_name`) VALUES ('Омская область');
INSERT INTO `regions`(`region_name`) VALUES ('Оренбургская область');
INSERT INTO `regions`(`region_name`) VALUES ('Орловская область');
INSERT INTO `regions`(`region_name`) VALUES ('Пензенская область');
INSERT INTO `regions`(`region_name`) VALUES ('Пермский край');
INSERT INTO `regions`(`region_name`) VALUES ('Псковская область');
INSERT INTO `regions`(`region_name`) VALUES ('Ростовская область');
INSERT INTO `regions`(`region_name`) VALUES ('Рязанская область');
INSERT INTO `regions`(`region_name`) VALUES ('Самарская область');
INSERT INTO `regions`(`region_name`) VALUES ('Саратовская область');
INSERT INTO `regions`(`region_name`) VALUES ('Сахалинская область');
INSERT INTO `regions`(`region_name`) VALUES ('Свердловская область');
INSERT INTO `regions`(`region_name`) VALUES ('Смоленская область');
INSERT INTO `regions`(`region_name`) VALUES ('Тамбовская область');
INSERT INTO `regions`(`region_name`) VALUES ('Тверская область');
INSERT INTO `regions`(`region_name`) VALUES ('Томская область');
INSERT INTO `regions`(`region_name`) VALUES ('Тульская область');
INSERT INTO `regions`(`region_name`) VALUES ('Тюменская область');
INSERT INTO `regions`(`region_name`) VALUES ('Ульяновская область');
INSERT INTO `regions`(`region_name`) VALUES ('Челябинская область');
INSERT INTO `regions`(`region_name`) VALUES ('Забайкальский край');
INSERT INTO `regions`(`region_name`) VALUES ('Ярославская область');
INSERT INTO `regions`(`region_name`) VALUES ('Москва');
INSERT INTO `regions`(`region_name`) VALUES ('Санкт-Петербург');
INSERT INTO `regions`(`region_name`) VALUES ('Еврейская автономная область');
INSERT INTO `regions`(`region_name`) VALUES ('Ненецкий автономный округ');
INSERT INTO `regions`(`region_name`) VALUES ('Ханты-Мансийский автономный округ - Югра');
INSERT INTO `regions`(`region_name`) VALUES ('Чукотский автономный округ');
INSERT INTO `regions`(`region_name`) VALUES ('Ямало-Ненецкий автономный округ');
INSERT INTO `regions`(`region_name`) VALUES ('Республика Крым');
INSERT INTO `regions`(`region_name`) VALUES ('Севастополь');
INSERT INTO `regions`(`region_name`) VALUES ('Байконур');